web/cpe/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = "components"

urlpatterns = [
    path('', views.index, name='index'),
    path('add',views.add_cpe, name='add'),
    path('get_dropdown',views.get_dropdown, name='get_dropdown'),
    path('get_table',views.get_table, name='get_table'),
    path('get_components',views.get_components, name='get_components'),
    path('get_template',views.get_template, name='get_template'),
    path('get_versions',views.get_versions, name='get_versions'),
    path('save_template',views.save_template, name='save_template'),
    path('save_components',views.save_components, name='save_components'),
    path('add_from_template',views.add_from_template, name='add_from_template'),
    path('autocomplete', views.autocomplete, name='autocomplete'),
] + staticfiles_urlpatterns()

web/cve/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = "Vulnerabilities"

urlpatterns = [
    path('', views.index, name='index'),
    path('get', views.get_vuln, name='get'),
    path('update', views.update_vuln, name='update'),
    path('query', views.query_vuln, name='query'),
] + staticfiles_urlpatterns()

web/vms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', views.profile, name='profile'),
    path('accountmanager/', views.accountmanager, name='accountmanager'),
    path('components/', include('cpe.urls', namespace = 'components')),
    path('vulnerabilities/', include('cve.urls', namespace = 'vulnerabilities')),
    path('products/', include('products.urls', namespace = 'products')),
    path('notifications/', include('notifications.urls', namespace = 'notifications')),
    path('', views.home, name='home'),
] + staticfiles_urlpatterns()

web/cve/models.py
from django.db import models
from cpe.models import component_to_server
from products.models import server

class vulnerability(models.Model):

    id = models.AutoField(primary_key=True)
    cve_id = models.CharField(max_length=16)
    summary = models.TextField()
    published = models.DateTimeField()
    last_modified = models.DateTimeField()
    score_v3 = models.DecimalField(max_digits=3,decimal_places=1)
    score_v2 = models.DecimalField(max_digits=3,decimal_places=1)
    vector_string_v2 = models.CharField(max_length=100)
    vector_string_v3 = models.CharField(max_length=100)
    in_date = models.DateTimeField(auto_now_add=True)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.cve_id

class affects(models.Model):
    id = models.AutoField(primary_key=True)
    cve = models.ForeignKey(vulnerability, on_delete=models.CASCADE)
    c2s = models.ForeignKey(component_to_server, on_delete=models.CASCADE)
    server = models.ForeignKey(server, on_delete=models.CASCADE)
    custom_score = models.DecimalField(max_digits=3,decimal_places=1)
    comments = models.TextField()
    timestamp = models.DateTimeField(auto_now=True)

web/cve/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import affects
from django.db.models import F
from django.http import HttpResponse, JsonResponse
from products.models import product
from datetime import datetime
from cpe.models import component_to_server,component
from vms.settings import USE_ELASTIC_SEARCH

@login_required
def index(request,error=False):
    product_list = product.objects.filter(user=request.user)
    context = {'products': product_list}
    if error is True:
        context['error'] = True
    return render(request, 'cve/index.html', context)

@login_required
def get_vuln(request):
    if 'affect-id' in request.POST:
        context = {}
        if affects.objects.filter(id=float(request.POST['affect-id']),server__product__user=request.user).exists():
            results = affects.objects.filter(id=float(request.POST['affect-id']),server__product__user=request.user).annotate(
                vuln_cve=F('cve__cve_id'),
                product_name=F('server__product__name'),
                server_name=F('server__name'),
                component_name=F('c2s__cpe__cpe_id'),
                component_title=F('c2s__cpe__title'),
                summary=F('cve__summary'),
                published=F('cve__published'),
                last_modified=F('cve__last_modified'),
                in_date=F('cve__in_date'),
                score_v3=F('cve__score_v3'),
                vector_sting_v3=F('cve__vector_string_v3'),
                score_v2=F('cve__score_v2'),
                vector_sting_v2=F('cve__vector_string_v2')
                )
            context['results'] = results[0]
        print(context)
        return render(request, 'cve/get_vuln.html', context)
    return index(request)

@login_required
def update_vuln(request):
    if 'affect-id' in request.POST:
        if affects.objects.filter(id=float(request.POST['affect-id']),server__product__user=request.user).exists():
            obj = affects.objects.get(id=float(request.POST['affect-id']),server__product__user=request.user)
            obj.comments = request.POST["comments"]
            obj.custom_score = request.POST["custom_score"]
            obj.save()
            return HttpResponse("Successfully updated!")
        else:
            return HttpResponse("Unknown error occured!")
    else:
        return index(request)

@login_required
def query_vuln(request):
    print(request.POST)
    try:
        datetime.strptime(request.POST['from_date'], "%Y-%m-%d")
        datetime.strptime(request.POST['to_date'], "%Y-%m-%d")
    except ValueError:
        return index(request,error=True)
    if 'product' in request.POST:
        context = {}
        try:
            if request.POST['product'] is '':
                vuln_list = affects.objects.filter(server__product__user=request.user,cve__published__range=[request.POST['from_date'],request.POST['to_date']]).annotate(
                    product_name=F('server__product__name'),
                    server_name=F('server__name'),
                    component_name=F('c2s__cpe__cpe_id'),
                    component_title=F('c2s__cpe__title'),
                    vuln_cve=F('cve__cve_id'),
                    score_v3=F('cve__score_v3'),
                    score_v2=F('cve__score_v2'),
                    published=F('cve__published')
                )
                context['header'] = 'All Products'
            else:
                vuln_list = affects.objects.filter(server__product__user=request.user,server__product__id=request.POST['product'],cve__published__range=[request.POST['from_date'],request.POST['to_date']]).annotate(
                    product_name=F('server__product__name'),
                    server_name=F('server__name'),
                    component_name=F('c2s__cpe__cpe_id'),
                    component_title=F('c2s__cpe__title'),
                    vuln_cve=F('cve__cve_id'),
                    score_v3=F('cve__score_v3'),
                    score_v2=F('cve__score_v2'),
                    published=F('cve__published')
                )
                context['header'] = product.objects.get(id=request.POST['product']).name
            context['results'] = vuln_list
            return render(request, 'cve/query.html', context)
        except:
            return index(request,error=True)
    elif 'cpe' in request.POST:
        context = {}
        if request.POST['cpe'] is '':
            return index(request,error=True)
        vuln_list = affects.objects.filter(server__product__user=request.user,cve__published__range=[request.POST['from_date'],request.POST['to_date']],c2s__cpe__id=request.POST['cpe']).annotate(
            product_name=F('server__product__name'),
            server_name=F('server__name'),
            component_name=F('c2s__cpe__cpe_id'),
            component_title=F('c2s__cpe__title'),
            vuln_cve=F('cve__cve_id'),
            score_v3=F('cve__score_v3'),
            score_v2=F('cve__score_v2'),
            published=F('cve__published')
        )
        context['header'] = component_to_server.objects.get(id=request.POST["cpe"]).cpe.title
        context['results'] = vuln_list
        context['product'] = True
        return render(request, 'cve/query.html', context)
    else:
        return index(request)

web/cve/templates/cve/get_vuln.html
<form id="update-vuln">
  {% csrf_token %}
  <input type="hidden" name="affect-id" value="{{results.id}}"/>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="modal-title">{{results.vuln_cve}}</h4>
  </div>
  <div class="modal-body" id="modal-body">
    <div class="row">
      <div class="col-md-6">
        <strong>Product:</strong> {{results.product_name}}<br>
        <strong>Affected Component:</strong> {{results.component_name}}<br>
      </div>
      <div class="col-md-6">
        <strong>Server:</strong> {{results.server_name}}<br>
        <strong>Component Name: </strong> {{results.component_title}}
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <textarea rows="5" class="form-control" disabled> {{results.summary}}</textarea>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <strong>Published:</strong> {{results.published}}<br>
        <strong>Last Modified:</strong> {{results.last_modified}}<br>
        <strong>Date of adding to DB:</strong> {{results.in_date}}<br>
        <strong>Comments:</strong>
        <textarea rows="4" cols="50" class="form-control" name="comments" id="comments">{{results.comments}}</textarea>
      </div>
      <div class="col-md-6">
        <strong>Score v3:</strong> {% if results.score_v3 == 0.0 %}NA{% else %}{{results.score_v3}}{% endif %} <br>
        <strong>Vector String v3:</strong> {% if results.vector_sting_v3 == '' %}NA{% else %}{{results.vector_sting_v3}}{% endif %}<br>
        <strong>Score v2:</strong> {% if results.score_v2 == 0.0 %}NA{% else %}{{results.score_v2}}{% endif %} <br>
        <strong>Vector String v2:</strong> {% if results.vector_sting_v2 == '' %}NA{% else %}{{results.vector_sting_v2}}{% endif %}<br>
        <strong>Custom Score:</strong>
        <input id="custom_score" name="custom_score" type="number" step="0.1" min="0.0" max="10.0" class="form-control" value="{{results.custom_score}}"/>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button id="update-vuln-button" type="submit" class="btn btn-primary">Save changes</button>
  </div>
</form>

web/cve/templates/cve/index.html
{% extends 'main/base.html' %}
{% block color %}purple{% endblock color %}
{% block title %}
VMS - Vulnerabilities
{% endblock title %}
{% block css %}
<link href="/static/main/css/dataTables.material.min.css" rel="stylesheet" />
<link href="/static/main/css/material.min.css" rel="stylesheet" />
<link href="/static/main/css/typeahead.css" rel="stylesheet" />
{% endblock css %}
{% block heading %}
CVE
{% endblock heading %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8" id="alerts"></div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
          <div class="card-header" data-background-color="purple">
              <h4 class="title">Query</h4>
              <p class="category">
              Select Parameters
              </p>
          </div>
          <div class="card-content">
              <form id="query-form" action="{% url 'vulnerabilities:query' %}" method="POST">
                <input type="hidden" id="selected-product" name="product"/>
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-md-4">
                      <div class="dropdown" id="products-dropdown">
                        <button id="product-name" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">All Product
                          <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                          {% for i in products %}
                          <li><a href="#" id="{{i.id}}" value="{{i.name}}">{{i.name}}</a></li>
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                    <div class="col-md-4">
                      <label class="control-label">From Date</label>
                      <input class="form-control" type="date" name="from_date" id="from-date" />
                    </div>
                    <div class="col-md-4">
                      <label class="control-label">To Date</label>
                      <input class="form-control" type="date" name="to_date" id="to-date"/>
                    </div>
                  </div>
                  <button id="query-button" type="submit" class="btn btn-primary pull-right" id="submit-button" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Updating" >Get Vulnerabilities</button>
                  <div class="clearfix"></div>
              </form>
          </div>
      </div>
      <div class="card">
          <div class="card-header" data-background-color="purple">
              <h4 class="title">Query</h4>
              <p class="category">
              Select Parameters
              </p>
          </div>
          <div class="card-content">
              <form id="query-form2" action="{% url 'vulnerabilities:query' %}" method="POST">
                <input type="hidden" id="selected-component" name="cpe"/>
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-md-6">
                      <label class="control-label">Select Component</label>


                      <div id="autocomplete">
                        <input class="typeahead form-control" type="text"/>
                      </div>


                    </div>
                    <div class="col-md-3">
                      <label class="control-label">From Date</label>
                      <input class="form-control" type="date" name="from_date" id="from-date" />
                    </div>
                    <div class="col-md-3">
                      <label class="control-label">To Date</label>
                      <input class="form-control" type="date" name="to_date" id="to-date"/>
                    </div>
                  </div>
                  <button id="query-button" type="submit" class="btn btn-primary pull-right" id="submit-button" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Updating" >Get Vulnerabilities</button>
                  <div class="clearfix"></div>
              </form>
          </div>
      </div>
    </div>
  </div>
</div>
<form id="get-vuln">
  {% csrf_token %}
  <input type="hidden" name="affect-id" id="affect-id"/>
</form>

{% endblock content%}
{% block javascript %}
<script src='/static/main/js/typeahead.bundle.min.js'></script>
<script type="text/javascript">
$("#nav-vulns").addClass("active");

$(document).ready(function () {

  var components = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
      url: "{% url 'components:autocomplete' %}?search=%QUERY",
      wildcard: '%QUERY'
    }
  });

  $('#autocomplete .typeahead').typeahead(null, {
    name: 'components',
    display: 'name',
    limit: '1000000',
    source: components
  });

  $('.typeahead').on('typeahead:selected', function(evt, item) {
    $('#selected-component').val(item.id);
  });

  $("#products-dropdown a").click(function(){
    $('#selected-product').val($(this).attr('id'));
    $('#product-name').html($(this).attr('value')+' <span class="caret"></span>');
  });
  {% if error %}
    showNotification('bottom','right',"Invalid inputs!",'danger');
  {% endif %}
});
</script>
{% endblock javascript %}

web/cve/templates/cve/query.html
{% extends 'main/base.html' %}
{% block color %}purple{% endblock color %}
{% block title %}
VMS - Vulnerabilities
{% endblock title %}
{% block css %}
<link href="/static/main/css/dataTables.material.min.css" rel="stylesheet" />
<link href="/static/main/css/material.min.css" rel="stylesheet" />
{% endblock css %}
{% block heading %}
Query Results
{% endblock heading %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8" id="alerts"></div>
  </div>
  <div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="purple">
                <h4 class="title">Query Results</h4>
                <p class="category">{{header}}</p>
            </div>
            <div class="card-content">
              <div id="loading-text">
                Loading...
              </div>
              <div id="table-content" style="display:none;">
                <table id="data-table" class="mdl-data-table">
                  <thead>
                    <tr>
                      {% if product %}<th>Product</th>{% endif %}
                      <th>Server</th>
                      <th>CPE</th>
                      <th>CVE</th>
                      <th style="white-space:normal;">Score V2</th>
                      <th style="white-space:normal;">Score V3</th>
                      <th style="white-space:normal;">Custom Score</th>
                      <th>Comments</th>
                      <th style="white-space:normal;">Published Date</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for i in results %}
                    <tr data-toggle="modal" id="{{i.id}}" data-target="#detailModal">
                      {% if product %}<td>{{i.product_name}}</td>{% endif %}
                      <td>{{i.server_name}}</td>
                      <td>{{i.component_name}}</td>
                      <td>{{i.vuln_cve}}</td>
                      <td>{{i.score_v2}}</td>
                      <td>{% if i.score_v3 == 0.0 %}NA{% else %}{{i.score_v3}}{% endif %}</td>
                      <td>{% if i.custom_score == 0.0 %}NA{% else %}{{i.custom_score}}{% endif %}</td>
                      <td>{% if i.comments == '' %}NA{% else %}{{i.comments}}{% endif %}</td>
                      <td>{{i.published}}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
        </div>
    </div>
  </div>
</div>


<div id ="detailModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content" id="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-title">Loading..</h4>
      </div>
      <div class="modal-body" id="modal-body">
        Loading...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<form id="get-vuln">
  {% csrf_token %}
  <input type="hidden" name="affect-id" id="affect-id"/>
</form>

{% endblock content%}
{% block javascript %}
<script src='/static/main/js/jquery.dataTables.min.js'></script>
<script src='/static/main/js/dataTables.material.min.js'></script>
<script src='/static/main/js/dataTables.buttons.min.js'></script>
<script src='/static/main/js/jszip.min.js'></script>
<script src='/static/main/js/pdfmake.min.js'></script>
<script src='/static/main/js/vfs_fonts.js'></script>
<script src='/static/main/js/buttons.html5.min.js'></script>
<script src='/static/main/js/ellipsis.js'></script>
<script type="text/javascript">
$("#nav-vulns").addClass("active");
$(document).ready(function () {
  var tableOptions = {
    dom: 'Bfrtip',
    buttons: [
      {
        extend: 'pdf',
        text: 'Export as PDF',
        className: 'btn btn-primary pull-left',
        title: 'Vulnerability Report',
        messageTop: 'This is a system generated table',
        exportOptions: { orthogonal: 'export', columns: [ 0, 1, 2, 3, 4, 5, 6, 7 ] },
        pageSize: 'A4'
      },
      {
        extend: 'excel',
        text: 'Export as Excel',
        className: 'btn btn-primary pull-left',
        title: 'Vulnerability Report',
        messageTop: 'This is a system generated table',
        exportOptions: { orthogonal: 'export'},
        orientation: 'landscape',
        pageSize: 'A4',
      }
    ],
    autoWidth : true,
    fnInitComplete: function(oSettings) {
                        $( window ).resize();
                    },
    fnDrawCallback: function(oSettings) {
      $( window ).trigger('resize');
    },
    "scrollX": true,
    "scrollCollapse": true,
    "paging": true,
    "order": [[0, 'asc'],[ 1, 'asc' ],[ 4, 'desc' ],[ 5, 'desc' ],[ 6, 'desc' ]],
    columnDefs: [
      {targets: '_all', className: 'mdl-data-table__cell--non-numeric text-center'},
      {targets: [2],render: $.fn.dataTable.render.ellipsis(30)},
      {targets: [7],render: $.fn.dataTable.render.ellipsis(15)}
    ],
  };

  var table = $('#data-table').DataTable(tableOptions);
  $('#table-content').fadeIn();
  $('#loading-text').hide();

  var triggerRow;
  $('#detailModal').modal({
      keyboard: true,
      backdrop: "static",
      show:false,
    }).on('shown.bs.modal', function(e){
      triggerRow = $(e.relatedTarget);
      var rowID = triggerRow.attr('id');
      $("#affect-id").val(rowID);
      $.ajax({
        url : "{% url 'vulnerabilities:get' %}",
        type: "POST",
        data: $('#get-vuln').serialize(),
        success: function (data) {
          $('#modal-content').html(data);
        },
        error: function (jXHR, textStatus, errorThrown) {
          alert(errorThrown);
        }
      });
  });

  $('body').on('hidden.bs.modal','#detailModal',function(){
    comments = $('#comments').val()
    if(comments.length>15)
      comments = '<span class="ellipsis" title="' + comments + '">'+ comments.substring(0,14) +' ...</span>';
    else if(comments==='')
      comments = 'NA';
    score = $('#custom_score').val();
    if(score === '0.0')
      score = 'NA';
    $(triggerRow.children()[{% if product %}7{% else %}6{% endif %}]).html(comments);
    $(triggerRow.children()[{% if product %}6{% else %}5{% endif %}]).html(score);
    $('#modal-body').html('Loading...');
    $('#modal-title').html('Loading...');
  });

  $('body').on('submit','#update-vuln',function(e){
    e.preventDefault();
    $('#update-vuln-button').button("loading");
    $.ajax({
      url : "{% url 'vulnerabilities:update' %}",
      type: "POST",
      data: $('#update-vuln').serialize(),
      success: function (data) {
        $('#update-vuln-button').button("reset");
        $('#detailModal').modal('toggle');
        showNotification('bottom','right',data,'success');
      },
      error: function (jXHR, textStatus, errorThrown) {
        alert(errorThrown);
        $('#update-vuln-button').button("reset");
      }
    });
  });
});
</script>
{% endblock javascript %}