web/cpe/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = "components"

urlpatterns = [
    path('', views.index, name='index'),
    path('add',views.add_cpe, name='add'),
    path('get_dropdown',views.get_dropdown, name='get_dropdown'),
    path('get_table',views.get_table, name='get_table'),
    path('get_components',views.get_components, name='get_components'),
    path('get_template',views.get_template, name='get_template'),
    path('get_versions',views.get_versions, name='get_versions'),
    path('save_template',views.save_template, name='save_template'),
    path('save_components',views.save_components, name='save_components'),
    path('add_from_template',views.add_from_template, name='add_from_template'),
    path('autocomplete', views.autocomplete, name='autocomplete'),
] + staticfiles_urlpatterns()

web/vms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', views.profile, name='profile'),
    path('accountmanager/', views.accountmanager, name='accountmanager'),
    path('components/', include('cpe.urls', namespace = 'components')),
    path('vulnerabilities/', include('cve.urls', namespace = 'vulnerabilities')),
    path('products/', include('products.urls', namespace = 'products')),
    path('notifications/', include('notifications.urls', namespace = 'notifications')),
    path('', views.home, name='home'),
] + staticfiles_urlpatterns()

web/cpe/models.py
from django.db import models
from products.models import server
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User

class component(models.Model):

    id = models.AutoField(primary_key=True)
    cpe_id = models.CharField(max_length=255,blank=True)
    title = models.TextField(blank=True)
    wfs = models.CharField(max_length=255,blank=True)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.cpe_id

class component_to_server(models.Model):
    id = models.AutoField(primary_key=True)
    server = models.ForeignKey(server, on_delete=models.CASCADE)
    cpe = models.ForeignKey(component, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)

class template(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255,blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)

class template_to_cpe(models.Model):
    id = models.AutoField(primary_key=True)
    cpe = models.ForeignKey(component, on_delete=models.CASCADE)
    template = models.ForeignKey(template, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)

web/cpe/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .utils import cpe_handler, add_to_template, get_template as get_template_obj
from io import TextIOWrapper
from .models import component,component_to_server,template_to_cpe,template
from products.models import server,product
from django.db.models import F
from django.http import JsonResponse,HttpResponse
from .tasks import add_cpe_from_csv,add_rpm_from_file,add_rpm, save_components as save_comp
from cve.tasks import add_vuln,vulns_added_notif
from vms.settings import USE_ELASTIC_SEARCH, ELASTIC_SEARCH_URL
from celery import chain,chord
import json

@login_required
def index(request):
    context = {}
    if 'selected_cpe' in request.POST:
        for i in request.POST.getlist('selected_cpe'):
            if component_to_server.objects.filter(id=i).exists():
                component_to_server.objects.get(id=i).delete()
        context['deleted'] = True
        context['message'] = "Selected Items were deleted."
    product_list = product.objects.filter(user=request.user)
    context['products'] = product_list
    return render(request, 'cpe/index.html', context)

@login_required
def add_cpe(request):
    if 'cpe' in request.POST:
        if 'cpe:' in request.POST["cpe"]:
            obj = cpe_handler()
            r = obj.add_cpe(request.POST['cpe'],int(request.POST['server']))
            if r[0] == 0:
                return JsonResponse({"message": "Component not found!","type":"danger"})
            elif r[0] ==-1:
                return JsonResponse({"message": "Component already in database!","type":"warning"})
            elif r[0] ==-2:
                return JsonResponse({"message": "Unknown error occured","type":"danger"})
            else:
                task_id = chain(add_vuln.si([request.POST['cpe'],int(request.POST['server'])]),vulns_added_notif.si(1,request.user.id))()
                return JsonResponse({"message": "Component added successfully!","type":"success"})
        else:
            r = add_rpm(request.POST['cpe'],int(request.POST['server']),request.user)
            if r[3] == "Invalid RPM name":
                return JsonResponse({"message": "Invalid input!","type":"danger"})
            elif r[3] == "Already in DB":
                return JsonResponse({"message": "Component already in database!","type":"warning"})
            elif r[3] == "Unknown error occured":
                return JsonResponse({"message": r[3],"type":"danger"})
            elif r[3] == "Added to DB":
                task_id = chain(add_vuln.si([r[1],int(request.POST['server'])]),vulns_added_notif.si(1,request.user.id))()
                return JsonResponse({"message": "Component added successfully!","type":"success"})
            elif r[3] == "Multiple matches found":
                return JsonResponse({"message": r[3],"type":"warning"})
            else:
                return JsonResponse({"message": "Component not found","type":"danger"})

    elif 'file_location' in request.FILES:
        if 'save_template' in request.POST:
            template_name = request.POST['template_name']
        else:
            template_name = ''
        if request.POST["filetype"] == "csv":
            csv_file = TextIOWrapper(request.FILES['file_location'].file, encoding=request.encoding)
            task_id = add_cpe_from_csv.delay(csv_file.read(),request.user.id,template_name)
            return HttpResponse("Adding the components. Please Wait..")
        elif request.POST["filetype"] == "rpm":
            rpm_file = TextIOWrapper(request.FILES['file_location'].file, encoding=request.encoding)
            rpm_list = rpm_file.readlines()
            task_id = add_rpm_from_file.delay(rpm_list,int(request.POST["server"]),request.user.id,template_name)
            return HttpResponse("RPMs are bing added. Please wait.")
        else:
            return HttpResponse("Unknown Error occured!")
    else:
        return HttpResponse("Unknown Error occured!")

@login_required
def get_dropdown(request):
    context = {}
    if 'csrfmiddlewaretoken' in request.POST:
        server_list = server.objects.filter(product__id=int(request.POST['product']))
        context['servers'] = server_list
        return render(request, 'cpe/get_dropdown.html',context)
    else:
        return index(request)

@login_required
def get_table(request):
    cpe_list = component_to_server.objects.filter(server__product__user=request.user).annotate(
        server_name=F('server__name'),
        product_name=F('server__product__name'),
        cpe_id=F('cpe__cpe_id'),
        title=F('cpe__title')
    )
    result = []
    for item in cpe_list:
        row = []
        row.append("<input type='checkbox' name='selected_cpe' value=" + str(item.id) + " class='cpe-radio'/>")
        row.append(item.product_name)
        row.append(item.server_name)
        row.append(item.cpe_id)
        row.append(item.title)
        result.append(row)
    return JsonResponse({"data":result}, safe=False)

@login_required
def add_from_template(request):
    products = product.objects.filter(user=request.user)
    templates = template.objects.all()
    return render(request,'cpe/add_from_template.html',{"products": products,"templates":templates})

@login_required
def autocomplete(request):
    response = []
    if 'search' in request.GET and request.GET['search'] is not '':
        data = component.objects.filter(title__icontains=request.GET['search'])
        for item in data:
            response.append({"name": item.title,"id": item.id})
        return JsonResponse(response, safe=False)
    elif 'searchall' in request.GET and request.GET['searchall'] is not '':
        if USE_ELASTIC_SEARCH:
            from elasticsearch import Elasticsearch
            es = Elasticsearch(ELASTIC_SEARCH_URL)
            query = {"query" : {"match":{"title": request.GET['searchall']}}}
            res = es.search(index="cpe-names",body=query,size=100,request_timeout=60)
            for item in res["hits"]["hits"]:
                response.append({"name": item["_source"]["title"],"cpe": item["_source"]["cpe_id"],"id": 0})
        else:
            obj = cpe_handler()
            res = obj.get_all_cpe()
            for item in res:
                if request.GET['searchall'].lower() in res[item].lower():
                    response.append({"name": res[item],"cpe": item,"id": 0})


    return JsonResponse(response, safe=False)

@login_required
def get_components(request):
    result = []
    if 'server' in request.POST:
        ser = None
        if server.objects.filter(id=int(request.POST['server'])).exists():
            ser = server.objects.get(id=int(request.POST['server']))
        if ser is not None:
            cpes = component_to_server.objects.filter(server = ser)
            for item in cpes:
                result.append({"id": item.id, "cpe": item.cpe.cpe_id, "title": item.cpe.title})
    return JsonResponse(result, safe=False)

@login_required
def get_template(request):
    result = []
    if 'template' in request.POST:
        if template_to_cpe.objects.filter(template__id=int(request.POST["template"])).exists():
            for item in template_to_cpe.objects.filter(template__id=int(request.POST["template"])):
                result.append({"cpe": item.cpe.cpe_id, "title": item.cpe.title})
    return JsonResponse(result, safe=False)

@login_required
def save_template(request):
    if 'template' in request.POST:
        temp = get_template_obj(request.POST['template'],request.user.id)
        if temp is not None:
            obj = cpe_handler()
            table = json.loads(request.POST["table"])
            for item in table:
                add_to_template(temp,item['cpe'])
        return JsonResponse({"message": "Template " + temp.name + " created!","type": "success"});

    return JsonResponse({"message": "Uknown error occured!","type": "danger"});

@login_required
def save_components(request):
    if 'server' in request.POST:
        table = json.loads(request.POST["table"])
        print(table)
        task_id = save_comp.delay(int(request.POST['product']),int(request.POST['server']),table,request.user.id)
    return JsonResponse({"message": "Components are being added!","type": "info"});

@login_required
def get_versions(request):
    print(request.POST)
    if 'cpe' in request.POST:
        try:
            cpe_start = ':'.join(request.POST['cpe'].split(':')[:4])
        except:
            return HttpResponse('')
        version_list = []
        if 1==2: #elasticsearch part to do
            pass
        else:
            obj = cpe_handler()
            res = obj.get_all_cpe()
            for item in res:
                if item.startswith(cpe_start):
                    version_list.append({"version": item.split(':')[4],"cpe": item, "name": res[item]})
            return JsonResponse(version_list,safe=False)
    return HttpResponse('')

web/cpe/templates/cpe/add_multiple.html
{% extends 'main/base.html' %}
{% block color %}purple{% endblock color %}
{% block title %}
VMS - Products
{% endblock title %}
{% block css %}
<link href="/static/main/css/dataTables.material.min.css" rel="stylesheet" />
<link href="/static/main/css/material.min.css" rel="stylesheet" />
{% endblock css %}
{% block heading %}
CSV Upload Results
{% endblock heading %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="purple">
                <h4 class="title">Results</h4>
                <p class="category">Upload results</p>
            </div>
            <div class="card-content">
              <table id="data-table" class="dataTable table table-striped">
                <thead>
                  <tr>
                    <th>Product</th>
                    <th>Server</th>
                    <th>CPE</th>
                    <th>Title</th>
                    <th>Remarks</th>
                  </tr>
                </thead>
                <tbody>
                {% for i in results %}
                  <tr>
                    {% for j in i %}
                    <td {% if j == 'Not found' %}style="color: red;"{% elif j == 'Product not found' %}style="color: red;"{% elif j == 'Server not found' %}style="color: red;"{% elif j == 'Already in DB' %}style="color: purple;"{% elif j == 'Added to DB' %}style="color: #358c17"{% endif %}>{{j}}</td>
                    {% endfor %}
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
        </div>
    </div>
  </div>
</div>
{% endblock content%}
{% block javascript %}
<script src='/static/main/js/jquery.dataTables.min.js'></script>
<script src='/static/main/js/dataTables.material.min.js'></script>
<script src='/static/main/js/ellipsis.js'></script>
<script type="text/javascript">
$("#nav-components").addClass("active");
$(document).ready(function () {
  $('#data-table').DataTable( {
    "scrollY": "400px",
    "scrollCollapse": true,
    "paging": false,
    "order": [[ 4, 'desc' ],[ 0, 'asc' ],[ 1, 'asc' ],[ 3, 'asc' ]],
    columnDefs: [
      {targets: '_all', className: 'mdl-data-table__cell--non-numeric'},
      {targets: [4], searchable: false},
      {targets: [2],render: $.fn.dataTable.render.ellipsis(40)},
      {targets: [3],render: $.fn.dataTable.render.ellipsis(40)}
    ]
  });
});
</script>
{% endblock javascript %}

web/cpe/templates/cpe/get_dropdown.html
{% if servers %}
{% for i in servers %}
<li><a class="server-select" href="#" id="{{i.id}}" value="{{i.name}}">{{i.name}}</a></li>
{% endfor %}
{% endif %}

web/cpe/templates/cpe/index.html
{% extends 'main/base.html' %}
{% block color %}purple{% endblock color %}
{% block title %}
VMS - Components
{% endblock title %}
{% block css %}
<link href="/static/main/css/dataTables.material.min.css" rel="stylesheet" />
<link href="/static/main/css/material.min.css" rel="stylesheet" />
{% endblock css %}
{% block heading %}
Add Component
{% endblock heading %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
          <div class="card-header" data-background-color="purple">
              <h4 class="title">Add Component</h4>
              <p class="category">
              Enter CPE URI
              </p>
          </div>
          <div class="card-content">
              <form id="add-cpe" action="" method="POST" class="form">
                <input type="hidden" id="selected-product" name="product"/>
                <input type="hidden" id="selected-server" name="server"/>
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-md-6">
                      <div class="dropdown" id="products-dropdown">
                        <button id="product-name" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select Product
                          <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                          {% for i in products %}
                          <li><a href="#" id="{{i.id}}" value="{{i.name}}">{{i.name}}</a></li>
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="dropdown" id="servers-dropdown">
                        <button id="server-name" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select Server
                          <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" id="server-dropdown-area">
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                      <div class="col-md-12">
                          <div class="form-group label-floating">
                              <label >CPE URI</label>
                              <input name='cpe' type="text" class="form-control" placeholder="Enter CPE 2.2 URI or CPE 2.3 URI"/>
                          </div>
                      </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <a href="{% url 'components:add_from_template' %}"><span type="notsubmit" class="btn btn-warning pull-left">Advanced Add</span></a>
                    </div>
                    <div class="col-md-6">
                      <button id="add-cpe-button" type="submit" class="btn btn-primary pull-right" id="submit-button" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Updating" >Add Component</button>
                    </div>
                  </div>
              </form>
          </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="card">
          <div class="card-header" data-background-color="purple">
            <h4 class="title">Add Components from File</h4>
            <p class="category">
            Upload File
            </p>
          </div>
          <div class="card-content">
            <div class="row" id="rpm-selector" style="display:none;">
              <div class="col-md-6">
                <div class="dropdown" id="products-dropdown2">
                  <button id="product-name2" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select Product
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    {% for i in products %}
                    <li><a href="#" id="{{i.id}}" value="{{i.name}}">{{i.name}}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
              <div class="col-md-6">
                <div class="dropdown" id="servers-dropdown2">
                  <button id="server-name2" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select Server
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" id="server-dropdown-area2">
                  </ul>
                </div>
              </div>
            </div>
            <form id="file-query">
              {% csrf_token %}
              <input type="hidden" id="selected-product2" name="product"/>
              <input type="hidden" id="selected-server2" name="server"/>
              <div class="radio">
                <label>
                  <input type="radio" name="filetype" value="csv" id="csv-radio" checked>
                  CSV
                </label>
              </div>
              <div class="radio">
                <label>
                  <input type="radio" name="filetype" value="rpm" id="rpm-radio">
                  RPM List
                </label>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <input type="file" name="file_location" id="file_location"/>
                </div>
              </div>
              <div class="row">
                <div class="checkbox pull-left col-md-4">
                  <br>
                   <label>
                       <input type="checkbox" name="save_template" id="template-radio" value="save"/>
                         Save as Template
                   </label>
                </div>
                <div class="col-md-4">
                  <input type="text" class="form-control" name="template_name" id="template-name" placeholder="Template name" disabled/>
                </div>
                <div class="col-md-4">
                  <button type="submit" class="btn btn-primary pull-right" id="file-button" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Updating" >Add From File</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header" data-background-color="purple">
          <h4 class="title">Components</h4>
          <p class="category">View and delete components</p>
        </div>
        <div class="card-content">
          <form id="delete-form" method="POST" action="">
            {% csrf_token %}
            <button type="button" class="btn btn-danger pull-left" id="delete-button" data-toggle="modal" data-target="#confirmationModal">Delete</button>
            <table id="data-table" class="mdl-data-table">
              <thead>
                <tr>
                  <th>Select</th>
                  <th>Product</th>
                  <th>Server</th>
                  <th>CPE</th>
                  <th>Title</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
            <div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="Are you sure" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="confirmationModalLabel">Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Do you want to delete the selected items?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Go back</button>
                    <button type="submit" class="btn btn-danger" id="delete-confirm">Delete</button>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<form id="dropdown-form">
  {% csrf_token %}
  <input type='hidden' id="sel-pro" name='product'/>
</form>
{% endblock content%}
{% block javascript %}
<script src='/static/main/js/jquery.dataTables.min.js'></script>
<script src='/static/main/js/dataTables.material.min.js'></script>
<script src='/static/main/js/ellipsis.js'></script>
<script type="text/javascript">
$("#nav-components").addClass("active");
$(document).ready(function () {
  tableOptions = {
    "ajax": '{% url "components:get_table" %}',
    "scrollY":        "200px",
    "scrollCollapse": true,
    "paging": false,
    "order": [[ 1, 'asc' ], [ 2, 'asc' ],[ 4, 'asc' ]],
    columnDefs: [
      {targets: '_all', className: 'mdl-data-table__cell--non-numeric'},
      {targets: [3],render: $.fn.dataTable.render.ellipsis( 50)},
      {targets: [4],render: $.fn.dataTable.render.ellipsis( 70)}
    ]
  };
  var table = $('#data-table').DataTable(tableOptions);
  {% if deleted %}
  showNotification('bottom','right','{{message}}','success');
  {% endif %}
  $("#products-dropdown a").click(function(){
    $('#selected-product').val($(this).attr('id'));
    $('#sel-pro').val($(this).attr('id'));
    $('#product-name').html($(this).attr('value')+' <span class="caret"></span>');
    $('#server-name').html('Select Server <span class="caret"></span>');
    $('#selected-server').val('');
    $.ajax({
      url : '{% url "components:get_dropdown" %}',
      type: "POST",
      data: $('#dropdown-form').serialize(),
      success: function (data) {
        $('#server-dropdown-area').html(data);
      },
      error: function (jXHR, textStatus, errorThrown) {
        alert(errorThrown);
      }
    });
  });
  $('body').on('click', '#servers-dropdown a', function (){
    $('#selected-server').val($(this).attr('id'));
    $('#server-name').html($(this).attr('value')+' <span class="caret"></span>');
  });
  $('body').on('submit', '#add-cpe', function (e){
    e.preventDefault();
    $('#add-cpe-button').button("loading");
    if($('#selected-server').val() == '' || $('#selected-product').val() == '')
    {
      showNotification('bottom','right',"Select a server and product!",'danger');
      $('#add-cpe-button').button("reset");
    }
    else {
      $.ajax({
        url : '{% url "components:add" %}',
        type: "POST",
        data: $(this).serialize(),
        success: function (data) {
          $('#add-cpe-button').button("reset");
          showNotification('bottom','right',data.message,data.type);
          table.ajax.reload();
        },
        error: function (jXHR, textStatus, errorThrown) {
          alert(errorThrown);
          $('#add-cpe-button').button("reset");
        }
      });
    }
  });
  $('#file-query').on('submit',function(e){
    e.preventDefault();
    var formData = new FormData(this);
    $('#file-button').button("loading");
    if($("input[name='filetype']:checked").val() == 'rpm' && ($('#selected-server2').val() == '' || $('#selected-product2').val() == '' || $("#file_location").val() == ''))
    {
      showNotification('bottom','right',"Select a server and product and a file!",'danger');
      $('#file-button').button("reset");
      return;
    }
    $.ajax({
      type: "POST",
      enctype: 'multipart/form-data',
      url : '{% url "components:add" %}',
      data: formData,
      processData: false,
      contentType: false,
      cache: false,
      timeout: 600000,
      success: function (data) {
        $('#file-button').button("reset");
        showNotification('bottom','right',data,'success');
      },
      error: function (jXHR, textStatus, errorThrown) {
        alert(errorThrown);
        $('#file-button').button("reset");
      }
    });
  });
  $("#products-dropdown2 a").click(function(){
    $('#selected-product2').val($(this).attr('id'));
    $('#sel-pro').val($(this).attr('id'));
    $('#product-name2').html($(this).attr('value')+' <span class="caret"></span>');
    $('#server-name2').html('Select Server <span class="caret"></span>');
    $('#selected-server2').val('');
    $.ajax({
      url : '{% url "components:get_dropdown" %}',
      type: "POST",
      data: $('#dropdown-form').serialize(),
      success: function (data) {
        $('#server-dropdown-area2').html(data);
      },
      error: function (jXHR, textStatus, errorThrown) {
        alert(errorThrown);
      }
    });
  });
  $('body').on('click', '#servers-dropdown2 a', function (){
    $('#selected-server2').val($(this).attr('id'));
    $('#server-name2').html($(this).attr('value')+' <span class="caret"></span>');
  });
  $('#rpm-radio').on('click',function(){
    $('#rpm-selector').fadeIn();
  });
  $('#csv-radio').on('click',function(){
    $('#rpm-selector').fadeOut();
  });

  $('#template-radio').on('change',function(){
    if($(this).prop('checked') === true){
       $("#template-name").removeAttr("disabled");
    }
    else {
      $("#template-name").attr("disabled", "disabled");
    }
});
});
</script>
{% endblock javascript %}