web/cpe/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = "components"

urlpatterns = [
    path('', views.index, name='index'),
    path('add',views.add_cpe, name='add'),
    path('get_dropdown',views.get_dropdown, name='get_dropdown'),
    path('get_table',views.get_table, name='get_table'),
    path('get_components',views.get_components, name='get_components'),
    path('get_template',views.get_template, name='get_template'),
    path('get_versions',views.get_versions, name='get_versions'),
    path('save_template',views.save_template, name='save_template'),
    path('save_components',views.save_components, name='save_components'),
    path('add_from_template',views.add_from_template, name='add_from_template'),
    path('autocomplete', views.autocomplete, name='autocomplete'),
] + staticfiles_urlpatterns()

web/products/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = "products"

urlpatterns = [
    path('', views.index, name='index'),
    path('add',views.add_product, name='add'),
    path('servers',views.servers, name='servers'),
    path('add_server',views.add_server, name='add_server'),
    path('get_table',views.get_table, name='get_table'),
] + staticfiles_urlpatterns()

web/vms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', views.profile, name='profile'),
    path('accountmanager/', views.accountmanager, name='accountmanager'),
    path('components/', include('cpe.urls', namespace = 'components')),
    path('vulnerabilities/', include('cve.urls', namespace = 'vulnerabilities')),
    path('products/', include('products.urls', namespace = 'products')),
    path('notifications/', include('notifications.urls', namespace = 'notifications')),
    path('', views.home, name='home'),
] + staticfiles_urlpatterns()

web/products/models.py
from django.db import models
from django.contrib.auth.models import User


class product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255,blank=True,unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class server(models.Model):
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey(product, on_delete=models.CASCADE)
    name = models.CharField(max_length=255,blank=True)
    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('product', 'name',)

    def __str__(self):
        return self.name

web/products/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.db.models import F
from products.models import product,server
from django.http import HttpResponse,JsonResponse
from django.db.models import Count
import csv
from io import TextIOWrapper

# Create your views here.
@login_required
def index(request):
    context = {}
    if 'selected_products' in request.POST:
        for pid in request.POST.getlist("selected_products"):
            if product.objects.filter(id=pid).exists():
                product.objects.filter(id=pid).delete()
        context["deleted"] = True
        context["message"] = str(len(request.POST["selected_products"])) + ' products have been deleted!'
    return render(request, 'products/index.html', context)

@login_required
def add_product(request):
    if 'product' in request.POST:
        if product.objects.filter(name=request.POST['product']).exists():
            return HttpResponse("Product with the same name already exists!")
        else:
            pro = product(name=request.POST['product'],user=request.user)
            pro.save()
            return HttpResponse("Product has been added!")
    else:
        return index(request)

@login_required
def servers(request):
    product_list = product.objects.filter(user=request.user)
    context = {'products': product_list}
    if 'selected_servers' in request.POST:
        for sid in request.POST.getlist("selected_servers"):
            if server.objects.filter(id=sid).exists():
                server.objects.filter(id=sid).delete()
        context["deleted"] = True
        context["message"] = 'Selected servers have been deleted!'
    return render(request, 'products/server.html', context)

@login_required
def add_server(request):
    if 'server' in request.POST and 'product' is not '':
        pro = product.objects.get(id=request.POST['product'])
        if server.objects.filter(name=request.POST['server'],product=pro).exists():
            return HttpResponse("Server with the same name already exists!")
        else:
            ser = server(name=request.POST['server'],product=pro)
            ser.save()
            return HttpResponse("Server has been added!")
    elif 'file_location' in request.FILES:
        csv_file = TextIOWrapper(request.FILES['file_location'].file, encoding=request.encoding)
        data = csv.reader(csv_file)
        results = []
        for row in data:
            pro = None
            if product.objects.filter(name=row[0],user=request.user).exists():
                pro = product.objects.get(name=row[0],user=request.user)
            for item in row[1:]:
                if item is '':
                    continue
                if pro is not None:
                    if server.objects.filter(product=pro,name=item).exists():
                        i = [pro.name,item,"Server with same name exists"]
                    else:
                        ser = server(name=item,product=pro)
                        ser.save()
                        i = [pro.name,item,"Added to DB"]
                else:
                    i = [row[0],item,"Product not found"]
                results.append(i)
        context = {"results": results}
        return render(request, 'products/add_multiple.html', context)
    else:
        return index(request)

def get_table(request):
    if 'server' in request.GET:
        server_list = server.objects.filter(product__user=request.user).annotate(product_name=F('product__name'), cpe_count=Count('component_to_server'))
        result = []
        for item in server_list:
            row = []
            row.append("<input type='checkbox' name='selected_servers' value=" + str(item.id) + " class='servers-radio'/>")
            row.append(item.id)
            row.append(item.name)
            row.append(item.product_name)
            row.append(item.cpe_count)
            result.append(row)
        return JsonResponse({"data": result})
    elif 'product' in request.GET:
        product_list = product.objects.filter(user=request.user).annotate(server_count=Count('server'))
        result = []
        for item in product_list:
            row = []
            row.append("<input type='checkbox' name='selected_products' value=" + str(item.id) + " class='products-radio'/>")
            row.append(item.id)
            row.append(item.name)
            row.append(item.server_count)
            result.append(row)
        return JsonResponse({"data": result})
    else:
        return render(request,"home/index.html")

web/products/templates/products/add_multiple.html
{% extends 'main/base.html' %}
{% block color %}purple{% endblock color %}
{% block title %}
VMS - Servers
{% endblock title %}
{% block css %}
<link href="/static/main/css/dataTables.material.min.css" rel="stylesheet" />
<link href="/static/main/css/material.min.css" rel="stylesheet" />
{% endblock css %}
{% block heading %}
CSV Upload
{% endblock heading %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header" data-background-color="purple">
          <h4 class="title">Servers</h4>
          <p class="category">Upload results</p>
        </div>
        <div class="card-content">
          <table id="data-table" class="mdl-data-table">
            <thead>
              <tr>
                <th>Product Name</th>
                <th>Server Name</th>
                <th>Remarks</th>
              </tr>
            </thead>
            <tbody>
              {% for i in results %}
              <tr>
                {% for j in i %}
                <td {% if j == 'Server with same name exists' %}style="color: red;"{% elif j == 'Product not found' %}style="color: red;"{% elif j == 'Server with same name exists' %}style="color: purple;"{% elif j == 'Added to DB' %}style="color: #358c17"{% endif %}>{{j}}</td>
                {% endfor %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<form id="dropdown-form">
  {% csrf_token %}
  <input type='hidden' id="sel-pro" name='product'/>
</form>
{% endblock content%}
{% block javascript %}
<script src='/static/main/js/jquery.dataTables.min.js'></script>
<script src='/static/main/js/dataTables.material.min.js'></script>
<script src='/static/main/js/ellipsis.js'></script>
<script type="text/javascript">
$("#nav-servers").addClass("active");
$(document).ready(function () {
  tableOptions = {
    "scrollY":        "400px",
    "scrollCollapse": true,
    "paging": false,
    "order": [[ 2, 'desc' ], [ 0, 'asc' ], [ 1, 'asc' ]],
    columnDefs: [
      {targets: '_all', className: 'mdl-data-table__cell--non-numeric'},
    ]
  };
  $('#data-table').DataTable(tableOptions);

});
</script>
{% endblock javascript %}

web/products/templates/products/index.html
{% extends 'main/base.html' %}
{% block color %}purple{% endblock color %}
{% block title %}
VMS - Products
{% endblock title %}
{% block css %}
<link href="/static/main/css/dataTables.material.min.css" rel="stylesheet" />
<link href="/static/main/css/material.min.css" rel="stylesheet" />
{% endblock css %}
{% block heading %}
Manage Products
{% endblock heading %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8" id="alerts"></div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
          <div class="card-header" data-background-color="purple">
              <h4 class="title">Add Product</h4>
              <p class="category">
              Enter Product Details
              </p>
          </div>
          <div class="card-content">
              <form id="add-product" action="" method="POST" class="form">
                  {% csrf_token %}
                  <div class="row">
                      <div class="col-md-12">
                          <div class="form-group label-floating">
                              <input name='product' type="text" class="form-control" placeholder="Product Name" id='product'/>
                          </div>
                      </div>
                  </div>
                  <button id="add-product-button" type="submit" class="btn btn-primary pull-right" id="submit-button" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Updating" >Add Product</button>
                  <div class="clearfix"></div>
              </form>
          </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header" data-background-color="purple">
          <h4 class="title">Products</h4>
          <p class="category">View and delete products</p>
        </div>
        <div class="card-content">
          <form id="delete-form" method="POST" action="">
            {% csrf_token %}
            <button type="button" class="btn btn-danger pull-left" id="delete-button" data-toggle="modal" data-target="#confirmationModal">Delete</button>
            <table id="data-table" class="mdl-data-table">
              <thead>
                <tr>
                  <th>Select</th>
                  <th>ID</th>
                  <th>Product Name</th>
                  <th>Number of Servers</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
            <div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="Are you sure" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="confirmationModalLabel">Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Do you want to delete the selected items?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Go back</button>
                    <button type="submit" class="btn btn-danger" id="delete-confirm">Delete</button>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<form id="dropdown-form">
  {% csrf_token %}
  <input type='hidden' id="sel-pro" name='product'/>
</form>
{% endblock content%}
{% block javascript %}
<script src='/static/main/js/jquery.dataTables.min.js'></script>
<script src='/static/main/js/dataTables.material.min.js'></script>
<script src='/static/main/js/ellipsis.js'></script>
<script type="text/javascript">
$("#nav-products").addClass("active");
$(document).ready(function () {
  tableOptions = {
    ajax: "{% url 'products:get_table' %}?product",
    "scrollY":        "300px",
    "scrollCollapse": true,
    "paging": false,
    "order": [[ 1, 'asc' ], [ 2, 'asc' ]],
    columnDefs: [
      {targets: '_all', className: 'mdl-data-table__cell--non-numeric'},
    ]
  };
  var table = $('#data-table').DataTable(tableOptions);

  {% if deleted %}
  showNotification('bottom','right','{{message}}','success');
  {% endif %}


  $('body').on('submit', '#add-product', function (e){
    e.preventDefault();
    $('#add-product-button').button("loading");
    if($('#product').val() == '')
    {
      showNotification('bottom','right',"Please input a product name",'danger');
      $('#add-product-button').button("reset");
    }
    else {
      $.ajax({
        url : '{% url "products:add" %}',
        type: "POST",
        data: $(this).serialize(),
        success: function (data) {
          $('#add-product-button').button("reset");
          showNotification('bottom','right',data,'success');
          table.ajax.reload();
          $('#product').val('');
        },
        error: function (jXHR, textStatus, errorThrown) {
          alert(errorThrown);
          $('#add-product-button').button("reset");
        }
      });
    }
  });
});
</script>
{% endblock javascript %}

web/products/templates/products/server.html
{% extends 'main/base.html' %}
{% block color %}purple{% endblock color %}
{% block title %}
VMS - Servers
{% endblock title %}
{% block css %}
<link href="/static/main/css/dataTables.material.min.css" rel="stylesheet" />
<link href="/static/main/css/material.min.css" rel="stylesheet" />
{% endblock css %}
{% block heading %}
Manage servers
{% endblock heading %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8" id="alerts"></div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="card">
          <div class="card-header" data-background-color="purple">
              <h4 class="title">Add Server</h4>
              <p class="category">
              Enter Server Details
              </p>
          </div>
          <div class="card-content">
              <form id="add-server" action="" method="POST" class="form">
                <input type="hidden" id="selected-product" name="product"/>
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-md-6">
                      <div class="dropdown" id="products-dropdown">
                        <button id="product-name" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select Product
                          <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                          {% for i in products %}
                          <li><a href="#" id="{{i.id}}" value="{{i.name}}">{{i.name}}</a></li>
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                      <div class="col-md-12">
                          <div class="form-group label-floating">
                              <input name='server' id="server" type="text" class="form-control" placeholder="Enter Server Name"/>
                          </div>
                      </div>
                  </div>

                  <button id="add-server-button" type="submit" class="btn btn-primary pull-right" id="submit-button" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Updating" >Add Server</button>
                  <div class="clearfix"></div>
              </form>
          </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
          <div class="card-header" data-background-color="purple">
              <h4 class="title">Add Servers from CSV</h4>
              <p class="category">
              Upload CSV File
              </p>
          </div>
          <div class="card-content">
              <form id="file-query" action="{% url 'products:add_server' %}" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="row">
                      <div class="col-md-12">
                              <input type="file" name="file_location" id="file_location"/>
                      </div>
                  </div>

                  <button type="submit" class="btn btn-primary pull-right" id="file-button" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Updating" >Add From File</button>
                  <div class="clearfix"></div>
              </form>
          </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header" data-background-color="purple">
          <h4 class="title">Servers</h4>
          <p class="category">View and delete servers</p>
        </div>
        <div class="card-content">
          <form id="delete-form" method="POST" action="">
            {% csrf_token %}
            <button type="button" class="btn btn-danger pull-left" id="delete-button" data-toggle="modal" data-target="#confirmationModal">Delete</button>
            <table id="data-table" class="mdl-data-table">
              <thead>
                <tr>
                  <th>Select</th>
                  <th>Server ID</th>
                  <th>Name</th>
                  <th>Product Name</th>
                  <th>Number of components</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
            <div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="Are you sure" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="confirmationModalLabel">Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Do you want to delete the selected items?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Go back</button>
                    <button type="submit" class="btn btn-danger" id="delete-confirm">Delete</button>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<form id="dropdown-form">
  {% csrf_token %}
  <input type='hidden' id="sel-pro" name='product'/>
</form>
{% endblock content%}
{% block javascript %}
<script src='/static/main/js/jquery.dataTables.min.js'></script>
<script src='/static/main/js/dataTables.material.min.js'></script>
<script src='/static/main/js/ellipsis.js'></script>
<script type="text/javascript">
$("#nav-servers").addClass("active");
$(document).ready(function () {
  tableOptions = {
    ajax: "{% url 'products:get_table' %}?server",
    "scrollY":        "200px",
    "scrollCollapse": true,
    "paging": false,
    "order": [[ 3, 'asc' ], [ 1, 'asc' ], [ 2, 'asc' ]],
    columnDefs: [
      {targets: '_all', className: 'mdl-data-table__cell--non-numeric'},
    ]
  };
  var table = $('#data-table').DataTable(tableOptions);

  {% if deleted %}
  showNotification('bottom','right','{{message}}','success');
  {% endif %}

  $("#products-dropdown a").click(function(){
    $('#selected-product').val($(this).attr('id'));
    $('#product-name').html($(this).attr('value')+' <span class="caret"></span>');
  });


  $('body').on('submit', '#add-server', function (e){
    e.preventDefault();
    $('#add-server-button').button("loading");
    if($('#server').val() == '' || $('#selected-product').val() == '')
    {
      showNotification('bottom','right',"Select a product and enter a server name!",'danger');
      $('#add-server-button').button("reset");
    }
    else {
      $.ajax({
        url : '{% url "products:add_server" %}',
        type: "POST",
        data: $(this).serialize(),
        success: function (data) {
          $('#add-server-button').button("reset");
          showNotification('bottom','right',data,'success');
          table.ajax.reload();
          $('#server').val('');
        },
        error: function (jXHR, textStatus, errorThrown) {
          alert(errorThrown);
          $('#add-server-button').button("reset");
        }
      });
    }
  });
});
</script>
{% endblock javascript %}