web/cpe/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = "components"

urlpatterns = [
    path('', views.index, name='index'),
    path('add',views.add_cpe, name='add'),
    path('get_dropdown',views.get_dropdown, name='get_dropdown'),
    path('get_table',views.get_table, name='get_table'),
    path('get_components',views.get_components, name='get_components'),
    path('get_template',views.get_template, name='get_template'),
    path('get_versions',views.get_versions, name='get_versions'),
    path('save_template',views.save_template, name='save_template'),
    path('save_components',views.save_components, name='save_components'),
    path('add_from_template',views.add_from_template, name='add_from_template'),
    path('autocomplete', views.autocomplete, name='autocomplete'),
] + staticfiles_urlpatterns()

web/cve/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = "Vulnerabilities"

urlpatterns = [
    path('', views.index, name='index'),
    path('get', views.get_vuln, name='get'),
    path('update', views.update_vuln, name='update'),
    path('query', views.query_vuln, name='query'),
] + staticfiles_urlpatterns()

web/products/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = "products"

urlpatterns = [
    path('', views.index, name='index'),
    path('add',views.add_product, name='add'),
    path('servers',views.servers, name='servers'),
    path('add_server',views.add_server, name='add_server'),
    path('get_table',views.get_table, name='get_table'),
] + staticfiles_urlpatterns()

web/vms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', views.profile, name='profile'),
    path('accountmanager/', views.accountmanager, name='accountmanager'),
    path('components/', include('cpe.urls', namespace = 'components')),
    path('vulnerabilities/', include('cve.urls', namespace = 'vulnerabilities')),
    path('products/', include('products.urls', namespace = 'products')),
    path('notifications/', include('notifications.urls', namespace = 'notifications')),
    path('', views.home, name='home'),
] + staticfiles_urlpatterns()

web/vms/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    return render(request, 'home/index.html')

@login_required
def profile(request):
    context = {
        'username': request.user.username,
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
        'email': request.user.email
    }
    return render(request, 'user/profile.html',context)

@login_required
def accountmanager(request):
    if 'old_password' in request.POST and 'new_password' in request.POST and 'new_password_again' in request.POST:
        old_pass = request.POST['old_password']
        new_pass = request.POST['new_password']
        new_pass2 = request.POST['new_password_again']
        if request.user.check_password(old_pass):
            if new_pass == new_pass2:
                if len(new_pass) > 8:
                    request.user.set_password(new_pass)
                    return render(request, 'user/update.html',{'password':True})
                else:
                    return render(request, 'user/update.html',{'weak':True})
            else:
                return render(request, 'user/update.html',{'mismatch':True})
        else:
            return render(request, 'user/update.html',{'wrongpassword':True})
    elif request.POST['userid']:
        username = request.POST['userid']
        fname = request.POST['first_name']
        lname = request.POST['last_name']
        email = request.POST['email']
        if fname is not "" and lname is not "" and email is not "":
            request.user.first_name = fname
            request.user.last_name = lname
            request.user.email = email
            request.user.save()
            return render(request, 'user/update.html',{'update':True})
        else:
            return render(request, 'user/update.html',{'emptyfield':True})
    else:
        return profile(request)

web/vms/templates/main/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>{% block title %}{% endblock title %}</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <link href="/static/main/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/static/main/css/material-dashboard.css?v=1.2.0" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons" rel='stylesheet'>
    {% block css %}{% endblock css %}
</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-color="{% block color %}{% endblock color %}" data-image="/static/main/images/sidebar-1.jpg">

            <div class="logo">
                <a href="{% url 'home' %}" class="simple-text">
                    VMS
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li id="nav-dash">
                        <a href="{% url 'home' %}">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li id="nav-user">
                        <a href="{% url 'profile' %}">
                            <i class="material-icons">person</i>
                            <p>User Profile</p>
                        </a>
                    </li>

                    <li id="nav-notifications">
                        <a href="{% url 'notifications:index' %}">
                            <i class="material-icons text-gray">notifications</i>
                            <p>Notifications</p>
                        </a>
                    </li>

                    <li id="nav-products">
                        <a href="{% url 'products:index' %}">
                            <i class="material-icons text-gray">work</i>
                            <p>Products</p>
                        </a>
                    </li>

                    <li id="nav-servers">
                        <a href="{% url 'products:servers' %}">
                            <i class="material-icons text-gray">dns</i>
                            <p>Servers</p>
                        </a>
                    </li>

                    <li id="nav-components">
                        <a href="{% url 'components:index' %}">
                            <i class="material-icons text-gray">tab</i>
                            <p>Components</p>
                        </a>
                    </li>

                    <li id="nav-vulns">
                        <a href="{% url 'vulnerabilities:index' %}">
                            <i class="material-icons text-gray">warning</i>
                            <p>Vulnerabilities</p>
                        </a>
                    </li>


                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> {% block heading %}{% endblock heading %} </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="{% url 'notifications:index' %}" class="dropdown-toggle" data-toggle="dropdown" id="notif-dropdown">
                                    <i class="material-icons">notifications</i>
                                    <span class="notification" id="count-display"></span>
                                    <p class="hidden-lg hidden-md">Notifications</p>
                                </a>
                                <ul class="dropdown-menu" id="notification-div">
                                </ul>
                            </li>
                            <li>
                                <a href="{% url 'logout'%}?next={{request.path}}">
                                  <button rel="tooltip" title="Logout" class="btn btn-simple btn-xs" data-placement="bottom">
                                    <i class="material-icons">power_settings_new</i>
                                    <p class="hidden-lg hidden-md">Logout</p>
                                  </button>
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
            </nav>
            <div class="content">
              {% block content %}{% endblock content %}
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="{% url 'home' %}">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'logout'%}?next={{request.path}}">
                                    Logout
                                </a>
                            </li>

                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script>
                        <a href="http://techmahindra.com">Tech Mahindra</a>
                    </p>
                </div>
            </footer>
        </div>
    </div>
    <form action="" method="POST" id="notif-form">
      {% csrf_token %}
    </form>
</body>
<!--   Core JS Files   -->
<script src="/static/main/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<script src="/static/main/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/main/js/material.min.js" type="text/javascript"></script>
<script src="/static/main/js/arrive.min.js"></script>
<script src="/static/main/js/perfect-scrollbar.jquery.min.js"></script>
<script src="/static/main/js/bootstrap-notify.js"></script>
<script src="/static/main/js/material-dashboard.js?v=1.2.0"></script>
{% block javascript %}{% endblock javascript %}
<script type="text/javascript">
var flag = 1;
function checkNotifications(){
  $.ajax({
    url : '{% url "notifications:get" %}',
    type: "POST",
    data: $("#notif-form").serialize(),
    success: function (data) {
      $("#notification-div").html(data);
      $("#count-display").html($("#notif-count").val());
      if(!flag){
        flag = 1;
        showNotification("bottom","right","Connected to server","success");
      }
    },
    error: function (jXHR, textStatus, errorThrown) {
      if(flag){
        flag = 0;
        showNotification("bottom","right","Connectivity to server lost!","warning");
      }
    }
  });
}
$(document).ready(function () {
  checkNotifications();
  $("#notif-dropdown").on("click",checkNotifications);
  setInterval(checkNotifications,60000);
});
</script>


</html>